// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ledger.proto

#include "ledger.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_ledger_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_ledger_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_PbBootstrapEndpoint;
}  // namespace protobuf_ledger_2eproto
namespace top {
namespace kadmlia {
namespace pb {
class PbBootstrapEndpointDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PbBootstrapEndpoint>
      _instance;
} _PbBootstrapEndpoint_default_instance_;
class PbBootstrapCacheDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PbBootstrapCache>
      _instance;
} _PbBootstrapCache_default_instance_;
}  // namespace pb
}  // namespace kadmlia
}  // namespace top
namespace protobuf_ledger_2eproto {
static void InitDefaultsPbBootstrapEndpoint() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::top::kadmlia::pb::_PbBootstrapEndpoint_default_instance_;
    new (ptr) ::top::kadmlia::pb::PbBootstrapEndpoint();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::top::kadmlia::pb::PbBootstrapEndpoint::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PbBootstrapEndpoint =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPbBootstrapEndpoint}, {}};

static void InitDefaultsPbBootstrapCache() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::top::kadmlia::pb::_PbBootstrapCache_default_instance_;
    new (ptr) ::top::kadmlia::pb::PbBootstrapCache();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::top::kadmlia::pb::PbBootstrapCache::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_PbBootstrapCache =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsPbBootstrapCache}, {
      &protobuf_ledger_2eproto::scc_info_PbBootstrapEndpoint.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_PbBootstrapEndpoint.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PbBootstrapCache.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::kadmlia::pb::PbBootstrapEndpoint, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::kadmlia::pb::PbBootstrapEndpoint, ip_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::kadmlia::pb::PbBootstrapEndpoint, port_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::kadmlia::pb::PbBootstrapCache, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::kadmlia::pb::PbBootstrapCache, endpoints_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::top::kadmlia::pb::PbBootstrapEndpoint)},
  { 7, -1, sizeof(::top::kadmlia::pb::PbBootstrapCache)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::top::kadmlia::pb::_PbBootstrapEndpoint_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::top::kadmlia::pb::_PbBootstrapCache_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "ledger.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014ledger.proto\022\016top.kadmlia.pb\"/\n\023PbBoot"
      "strapEndpoint\022\n\n\002ip\030\001 \001(\t\022\014\n\004port\030\002 \001(\r\""
      "J\n\020PbBootstrapCache\0226\n\tendpoints\030\001 \003(\0132#"
      ".top.kadmlia.pb.PbBootstrapEndpointb\006pro"
      "to3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 163);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ledger.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_ledger_2eproto
namespace top {
namespace kadmlia {
namespace pb {

// ===================================================================

void PbBootstrapEndpoint::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PbBootstrapEndpoint::kIpFieldNumber;
const int PbBootstrapEndpoint::kPortFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PbBootstrapEndpoint::PbBootstrapEndpoint()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_ledger_2eproto::scc_info_PbBootstrapEndpoint.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:top.kadmlia.pb.PbBootstrapEndpoint)
}
PbBootstrapEndpoint::PbBootstrapEndpoint(const PbBootstrapEndpoint& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.ip().size() > 0) {
    ip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ip_);
  }
  port_ = from.port_;
  // @@protoc_insertion_point(copy_constructor:top.kadmlia.pb.PbBootstrapEndpoint)
}

void PbBootstrapEndpoint::SharedCtor() {
  ip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  port_ = 0u;
}

PbBootstrapEndpoint::~PbBootstrapEndpoint() {
  // @@protoc_insertion_point(destructor:top.kadmlia.pb.PbBootstrapEndpoint)
  SharedDtor();
}

void PbBootstrapEndpoint::SharedDtor() {
  ip_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PbBootstrapEndpoint::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PbBootstrapEndpoint::descriptor() {
  ::protobuf_ledger_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ledger_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PbBootstrapEndpoint& PbBootstrapEndpoint::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_ledger_2eproto::scc_info_PbBootstrapEndpoint.base);
  return *internal_default_instance();
}


void PbBootstrapEndpoint::Clear() {
// @@protoc_insertion_point(message_clear_start:top.kadmlia.pb.PbBootstrapEndpoint)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  port_ = 0u;
  _internal_metadata_.Clear();
}

bool PbBootstrapEndpoint::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:top.kadmlia.pb.PbBootstrapEndpoint)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string ip = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ip()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->ip().data(), static_cast<int>(this->ip().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "top.kadmlia.pb.PbBootstrapEndpoint.ip"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 port = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &port_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:top.kadmlia.pb.PbBootstrapEndpoint)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:top.kadmlia.pb.PbBootstrapEndpoint)
  return false;
#undef DO_
}

void PbBootstrapEndpoint::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:top.kadmlia.pb.PbBootstrapEndpoint)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ip = 1;
  if (this->ip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ip().data(), static_cast<int>(this->ip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "top.kadmlia.pb.PbBootstrapEndpoint.ip");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->ip(), output);
  }

  // uint32 port = 2;
  if (this->port() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->port(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:top.kadmlia.pb.PbBootstrapEndpoint)
}

::google::protobuf::uint8* PbBootstrapEndpoint::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:top.kadmlia.pb.PbBootstrapEndpoint)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ip = 1;
  if (this->ip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ip().data(), static_cast<int>(this->ip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "top.kadmlia.pb.PbBootstrapEndpoint.ip");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->ip(), target);
  }

  // uint32 port = 2;
  if (this->port() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->port(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:top.kadmlia.pb.PbBootstrapEndpoint)
  return target;
}

size_t PbBootstrapEndpoint::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:top.kadmlia.pb.PbBootstrapEndpoint)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string ip = 1;
  if (this->ip().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->ip());
  }

  // uint32 port = 2;
  if (this->port() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->port());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PbBootstrapEndpoint::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:top.kadmlia.pb.PbBootstrapEndpoint)
  GOOGLE_DCHECK_NE(&from, this);
  const PbBootstrapEndpoint* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PbBootstrapEndpoint>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:top.kadmlia.pb.PbBootstrapEndpoint)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:top.kadmlia.pb.PbBootstrapEndpoint)
    MergeFrom(*source);
  }
}

void PbBootstrapEndpoint::MergeFrom(const PbBootstrapEndpoint& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:top.kadmlia.pb.PbBootstrapEndpoint)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ip().size() > 0) {

    ip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ip_);
  }
  if (from.port() != 0) {
    set_port(from.port());
  }
}

void PbBootstrapEndpoint::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:top.kadmlia.pb.PbBootstrapEndpoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PbBootstrapEndpoint::CopyFrom(const PbBootstrapEndpoint& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:top.kadmlia.pb.PbBootstrapEndpoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PbBootstrapEndpoint::IsInitialized() const {
  return true;
}

void PbBootstrapEndpoint::Swap(PbBootstrapEndpoint* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PbBootstrapEndpoint::InternalSwap(PbBootstrapEndpoint* other) {
  using std::swap;
  ip_.Swap(&other->ip_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(port_, other->port_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PbBootstrapEndpoint::GetMetadata() const {
  protobuf_ledger_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ledger_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PbBootstrapCache::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PbBootstrapCache::kEndpointsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PbBootstrapCache::PbBootstrapCache()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_ledger_2eproto::scc_info_PbBootstrapCache.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:top.kadmlia.pb.PbBootstrapCache)
}
PbBootstrapCache::PbBootstrapCache(const PbBootstrapCache& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      endpoints_(from.endpoints_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:top.kadmlia.pb.PbBootstrapCache)
}

void PbBootstrapCache::SharedCtor() {
}

PbBootstrapCache::~PbBootstrapCache() {
  // @@protoc_insertion_point(destructor:top.kadmlia.pb.PbBootstrapCache)
  SharedDtor();
}

void PbBootstrapCache::SharedDtor() {
}

void PbBootstrapCache::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PbBootstrapCache::descriptor() {
  ::protobuf_ledger_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ledger_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PbBootstrapCache& PbBootstrapCache::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_ledger_2eproto::scc_info_PbBootstrapCache.base);
  return *internal_default_instance();
}


void PbBootstrapCache::Clear() {
// @@protoc_insertion_point(message_clear_start:top.kadmlia.pb.PbBootstrapCache)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  endpoints_.Clear();
  _internal_metadata_.Clear();
}

bool PbBootstrapCache::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:top.kadmlia.pb.PbBootstrapCache)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .top.kadmlia.pb.PbBootstrapEndpoint endpoints = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_endpoints()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:top.kadmlia.pb.PbBootstrapCache)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:top.kadmlia.pb.PbBootstrapCache)
  return false;
#undef DO_
}

void PbBootstrapCache::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:top.kadmlia.pb.PbBootstrapCache)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .top.kadmlia.pb.PbBootstrapEndpoint endpoints = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->endpoints_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->endpoints(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:top.kadmlia.pb.PbBootstrapCache)
}

::google::protobuf::uint8* PbBootstrapCache::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:top.kadmlia.pb.PbBootstrapCache)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .top.kadmlia.pb.PbBootstrapEndpoint endpoints = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->endpoints_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->endpoints(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:top.kadmlia.pb.PbBootstrapCache)
  return target;
}

size_t PbBootstrapCache::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:top.kadmlia.pb.PbBootstrapCache)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .top.kadmlia.pb.PbBootstrapEndpoint endpoints = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->endpoints_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->endpoints(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PbBootstrapCache::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:top.kadmlia.pb.PbBootstrapCache)
  GOOGLE_DCHECK_NE(&from, this);
  const PbBootstrapCache* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PbBootstrapCache>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:top.kadmlia.pb.PbBootstrapCache)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:top.kadmlia.pb.PbBootstrapCache)
    MergeFrom(*source);
  }
}

void PbBootstrapCache::MergeFrom(const PbBootstrapCache& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:top.kadmlia.pb.PbBootstrapCache)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  endpoints_.MergeFrom(from.endpoints_);
}

void PbBootstrapCache::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:top.kadmlia.pb.PbBootstrapCache)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PbBootstrapCache::CopyFrom(const PbBootstrapCache& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:top.kadmlia.pb.PbBootstrapCache)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PbBootstrapCache::IsInitialized() const {
  return true;
}

void PbBootstrapCache::Swap(PbBootstrapCache* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PbBootstrapCache::InternalSwap(PbBootstrapCache* other) {
  using std::swap;
  CastToBase(&endpoints_)->InternalSwap(CastToBase(&other->endpoints_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PbBootstrapCache::GetMetadata() const {
  protobuf_ledger_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ledger_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
}  // namespace kadmlia
}  // namespace top
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::top::kadmlia::pb::PbBootstrapEndpoint* Arena::CreateMaybeMessage< ::top::kadmlia::pb::PbBootstrapEndpoint >(Arena* arena) {
  return Arena::CreateInternal< ::top::kadmlia::pb::PbBootstrapEndpoint >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::top::kadmlia::pb::PbBootstrapCache* Arena::CreateMaybeMessage< ::top::kadmlia::pb::PbBootstrapCache >(Arena* arena) {
  return Arena::CreateInternal< ::top::kadmlia::pb::PbBootstrapCache >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
